CREATE TABLE IF NOT EXISTS USERS(
  ID INT PRIMARY KEY,
  USERNAME VARCHAR(50),
  PASSWORD VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ROLES(
  ID INT PRIMARY KEY,
  NAME VARCHAR(100)
);

INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES(1, 'Rick', '123');
INSERT INTO USERS(ID, USERNAME, PASSWORD) VALUES(2, 'Morty', '321');

INSERT INTO ROLES(ID, NAME) VALUES(1, 'ROLE_USER');
INSERT INTO ROLES(ID, NAME) VALUES(2, 'ROLE_MANAGER');
INSERT INTO ROLES(ID, NAME) VALUES(3, 'ROLE_ADMIN');
INSERT INTO ROLES(ID, NAME) VALUES(4, 'ROLE_SUPER_ADMIN');